### ISSUE TITLE
Issue when calls "max" function with posix ptime

### ISSUE THREAD

**Issue by 3t-dev** [mshepanski/quince#5]
Dear @mshepanski,

In the lastest quince version, it work well all of basic CRID operators vs column type timestamp mapping with posix ptime.

Unfortunately, I want to select value in range by min, max function. It work with primary type, eg: int, string, ... but throw exception with posix ptime type.
exception msg is: "expected column of type 7, received type was 8"

I guests that result of sql max is timestamp and it not jet convert to string in order to map with posix ptime.

My function call:
quince::queryboost::optional<boost::posix_time::ptime> maxTimes = table->select(quince::max((*table)->last_update));
maxTimes has 1 item but when call maxTimes.begin() it throw above exception.

Please consider and help me resolve this issue.

Thanks you.

**Comment by mshepanski** [comment]
Hi trinhthetranh,

This is just a quick reply to say I've seen your email and I will get onto the problem over the next week.

Regards,
--- Michael

## 

Michael Shepanski
Be a philosopher for a day: visit http://stepbackstepforward.com

**Comment by mshepanski** [comment]
Okay, I have made a fix on the dev branch. Could you please check that it does what you need, and if it does then I will merge to master.

**Comment by 3t-dev** [comment]
thank for quickly resolve, I'll try to test.

**Comment by mshepanski** [comment]
Forgot to mention: you will need to pull quince_postgresql (dev branch). 

## 

Michael Shepanski
Be a philosopher for a day: visit http://stepbackstepforward.com

**Comment by mshepanski** [comment]
I have merged the fix to the master branch of quince_postgresql, and I'm going to close the issue now. Please reopen it if you disagree.
